const moods = [
    {
        id: 1,
        image: "/icons/calm.png",
        alt: "Calm",
        title: "Calm Vibes 🌿",
        description: "Slow breaths, soft to hear, quiet mind, gentle melodies.",
        buttonText: "Explore ",
        bgColor: "bg-gradient-to-br from-blue-100 to-teal-50",
        borderColor: "border-blue-300",
       buttonColor: "bg-blue-300 hover:bg-blue-400",
        tag: "ambient",
        //bgImage: "/bg-calm.jpg",
      },
    {
      id: 2,
      image: "/icons/sad.png",
      alt: "Sad",
      title: "Sadness Soother 💧",
      description: "Sad vibes? Let's turn those tears into bass drops!",
      buttonText: "Explore ",
      bgColor: "bg-gradient-to-br from-purple-100 to-pink-50",
      borderColor: "border-purple-300",
      buttonColor: "bg-purple-300 hover:bg-purple-400",
      tag: "sad",
    },
    {
      id: 3,
      image: "/icons/energy.png",
      alt: "Energy",
      title: "Fire & Fury Mode 🔥",
      description: "Channel that anger into some high-energy tunes.",
      buttonText: "Explore ",
      bgColor: "bg-gradient-to-br from-red-100 to-pink-50",
      borderColor: "border-red-300",
      buttonColor: "bg-red-300 hover:bg-red-400",
      tag: "rock",
    },
    
    {
      id: 5,
      image: "/icons/lonely.png",
      alt: "Lonely",
      title: "Lonely Nights 🌙",
      description: "Find comfort in melodies that understand solitude.",
      buttonText: "Explore ",
      bgColor: "bg-gradient-to-br from-indigo-100 to-purple-50",
      borderColor: "border-indigo-300",
      buttonColor: "bg-indigo-300 hover:bg-indigo-400",
      tag: "acoustic",
    },
    {
        id:4 ,
        image: "/icons/happy.png",
        alt: "Happy",
        title: "Sunshine Mode ☀️",
        description: "Boost your mood with upbeat and cheerful tunes.",
        buttonText: "Explore ",
        bgColor: "bg-gradient-to-br from-pink-100 to-pink-50",
        borderColor: "border-pink-300",
        buttonColor: "bg-pink-300 hover:bg-pink-400",
        tag: "happy",
      },
    {
      id: 6,
      image: "/icons/focus.png",
      alt: "Focus",
      title: "Focus Mode 🎧",
      description: "Lock in. Deep focus. No distractions. Promodoro.",
      buttonText: "Explore ",
      bgColor: "bg-gradient-to-br from-emerald-100 to-green-50",
      borderColor: "border-emerald-300",
      buttonColor: "bg-emerald-300 hover:bg-emerald-400",
      tag: "instrumental",
    },
  ];

  export default moods;