const moods = [
    {
        id: 1,
        image: "/calm.png",
        alt: "Calm",
        title: "Calm",
        description: "Slow breaths, quiet mind, gentle melodies.",
        buttonText: "Explore->",
        bgColor: "bg-gradient-to-br from-blue-100 to-teal-50",
        borderColor: "border-blue-300",
       buttonColor: "bg-blue-500 hover:bg-blue-600",
        tag: "ambient",
        //bgImage: "/bg-calm.jpg",
      },
    {
      id: 2,
      image: "/sad.png",
      alt: "Sad",
      title: "Rainy Day Blues ☔",
      description: "Sad vibes? Let's turn those tears into bass drops!",
      buttonText: "Explore",
      bgColor: "bg-gradient-to-br from-purple-100 to-pink-50",
      borderColor: "border-purple-300",
      buttonColor: "bg-purple-500 hover:bg-purple-600",
      tag: "sad",
    },
    {
      id: 3,
      image: "/angry.png",
      alt: "Angry",
      title: "Fire & Fury Mode 🔥",
      description: "Explore->",
      buttonText: "Explore->",
      bgColor: "bg-gradient-to-br from-red-100 to-pink-50",
      borderColor: "border-red-300",
      buttonColor: "bg-red-500 hover:bg-red-600",
      tag: "rock",
    },
    
    {
      id: 5,
      image: "/lonely.png",
      alt: "Lonely",
      title: "Lonely Nights 🌙",
      description: "Explore->",
      buttonText: "Explore->",
      bgColor: "bg-gradient-to-br from-indigo-100 to-purple-50",
      borderColor: "border-indigo-300",
      buttonColor: "bg-indigo-500 hover:bg-indigo-600",
      tag: "acoustic",
    },
    {
        id:4 ,
        image: "/happy.png",
        alt: "Happy",
        title: "Sunshine Mode ☀️",
        description: "Explore->",
        buttonText: "Explore->",
        bgColor: "bg-gradient-to-br from-pink-100 to-pink-50",
        borderColor: "border-pink-300",
        buttonColor: "bg-pink-500 hover:bg-pink-600",
        tag: "happy",
      },
    {
      id: 6,
      image: "/focus.png",
      alt: "Focus",
      title: "Focus Mode 🎧",
      description: "Lock in. Deep focus. No distractions.",
      buttonText: "Explore->c",
      bgColor: "bg-gradient-to-br from-emerald-100 to-green-50",
      borderColor: "border-emerald-300",
      buttonColor: "bg-emerald-500 hover:bg-emerald-600",
      tag: "instrumental",
    },
  ];

  export default moods;